namespace: ecuaalejo2013-dev
labels:
  frontend: cmtx-web-frontend
  api:      cmtx-api-public
  data:     cmtx-api-data
  mongo:    cmtx-mongo
ports:
  http: 8080
  mongo: 27017
dns:
  namespace: openshift-dns
  cidr: "172.30.0.10/32"   # ajusta si tu nameserver es otro
