apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress
  namespace: ecuaalejo2013-dev
spec:
  podSelector: {}             # aplica a todos los pods del ns
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: dns  # etiqueta oficial para DNS en OCP
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }