apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress-fallback
  namespace: ecuaalejo2013-dev
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
  - to:
    - ipBlock:
        cidr: 172.30.0.0/16       
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }