apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}               # todos los pods del ns
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.dns.namespace | default "openshift-dns" }}
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: dns
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }
  {{- if .Values.dns.cidr }}
  - to:
    - ipBlock:
        cidr: {{ .Values.dns.cidr }}
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }
  {{- end }}
