apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress
  namespace: ecuaalejo2013-dev
spec:
  podSelector: {}                # aplica a TODOS los pods
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: dns   # <- etiqueta correcta para DNS en OCP
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }