apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}               # todos los pods del ns
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: dns
    - ipBlock:
        cidr: {{ .Values.dns.cidr | default "172.30.0.10/32" }}
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }
