apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-allow-dns-egress-by-ip
  namespace: ecuaalejo2013-dev
spec:
  podSelector: {}          # TODOS los pods del ns
  policyTypes: [Egress]
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.dns.cidr | default "172.30.0.10/32" }}  # IP del nameserver
    ports:
    - { protocol: UDP, port: 53 }
    - { protocol: TCP, port: 53 }