apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-api-to-data
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: {{ .Values.labels.data }} }
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector: { matchLabels: { app.kubernetes.io/name: {{ .Values.labels.api }} } }
    ports: [ { protocol: TCP, port: {{ .Values.ports.http }} } ]