apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-egress-api-to-data
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.api }}
  policyTypes: [Egress]
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.labels.data }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.http }}
