apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-egress-api-to-data
  namespace: ecuaalejo2013-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cmtx-api-public
  policyTypes: [Egress]
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: cmtx-api-data
    ports:
    - protocol: TCP
      port: 8080