apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-data-to-mongo
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: {{ .Values.labels.mongo }} }
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector: { matchLabels: { app.kubernetes.io/name: {{ .Values.labels.data }} } }
    ports: [ { protocol: TCP, port: {{ .Values.ports.mongo }} } ]