apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cmtx-np-egress-data-to-mongo
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.data }}
  policyTypes: [Egress]
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.labels.mongo }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.mongo }}
