name: deploy-network
on: { push: { branches: [ main ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ecuaalejo2013-dev
    - uses: azure/setup-helm@v4
    - name: Helm upgrade
      run: helm upgrade --install cmtx-network chart -n ecuaalejo2013-dev
