name: deploy-network
on: 
  push:
    branches: ["master"]
    paths:
      - 'chart/**'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Log in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      - name: Log in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ecuaalejo2013-dev
      - name: Verificar chart y lint
        run: |
          pwd
          ls -la
          test -f chart/Chart.yaml || (echo "NO existe ./chart/Chart.yaml" && exit 1)
          helm lint ./chart
      - name: Helm upgrade
        run: helm upgrade --install cmtx-network ./chart
